apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lotometrics-api
  namespace: lotometrics
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: lotometrics.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lotometrics-api
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lotometrics-web
  namespace: lotometrics
spec:
  ingressClassName: nginx
  rules:
    - host: lotometrics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lotometrics-web
                port:
                  number: 80
